comet online zarkzork-based html5 webchat
it's so cool please don't break it.
* json api Tests [14%]
  CLOSED: [2009-11-24 Tue 11:17]
  - [X] simple message
  - [ ] simple typer
  - [ ] topic event
  - [ ] room with 8 people and make shure that all get events
  - [ ] simple dialog
  - [ ] room enter event && get_mates
  - [ ] room_leave event && get_mates
* bugs
** text not always deletes after message arives
   add message id to typers and messages and make them queled.
** idle failure
   one some computers (home one) after long idle time polling stops working
** most browsers do not implements canvas text api so logo must be redone.  
** text don't fades away always.
* features
** zark-zork joke machine
  Let server create very rare messages something like.
  server: i'm so tired of reading logs. I'wish someone said that i'm
  so cool and nobody did. And if someone did, i could not tell nobody
  becouse they say i should keep your privasy. I't so hard beeing
  server.
** when name duplicates show error.
** add mutex on all operations that change class variables
** leave room link
** when leaving via timeout show last message
** -1- missed messages flag in the title
   use window.onblur and window.onfocus
